# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Formatting
markdown: redcarpet

redcarpet:
  extensions: [with_toc_data]

# Setup
title:               John Keiser
tagline:             'Building a world suited for laziness'
description:         Thoughts about code, Chef, UX, and philosophy.
url:                 http://jkeiser.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              John Keiser
  url:               https://twitter.com/jkeiser2
  email:             john@johnkeiser.com

# Custom vars
version:             1.0.0
